# Generated by Django 3.0.5 on 2020-04-17 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=1024)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
