# Generated by Django 3.0.5 on 2020-04-17 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
